import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { AdminService } from '../admin/admin.service';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  const adminService = app.get(AdminService);

  const questions: any[] = [];
  const level = 9;
  let questionId = 901;

  const add = (type: string, text: string, answer: string, opts?: string[]) => {
    questions.push({ id: questionId++, level, roundKey: 'round1', type, text, correct: answer, options: opts || null, isActive: true });
  };

  // LEVEL 9 — Expert: Mixed output tracing + deep error finding
  // Topics: Exception safety, CRTP, multiple inheritance, advanced virtual dispatch, move semantics, UB

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void speak() { cout << "A"; }\n  void call() { speak(); }\n};\nclass B : public A {\n  void speak() { cout << "B"; }\n};\nclass C : public B {\n  void speak() { cout << "C"; }\n};\nint main() {\n  A* arr[3];\n  arr[0] = new A();\n  arr[1] = new B();\n  arr[2] = new C();\n  for(int i=0;i<3;i++) arr[i]->call();\n}', 'ABC');
  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  A() { cout << "A"; }\n  virtual ~A() { cout << "~A"; }\n};\nclass B : virtual public A {\npublic:\n  B() { cout << "B"; }\n  ~B() { cout << "~B"; }\n};\nclass C : virtual public A {\npublic:\n  C() { cout << "C"; }\n  ~C() { cout << "~C"; }\n};\nclass D : public B, public C {\npublic:\n  D() { cout << "D"; }\n  ~D() { cout << "~D"; }\n};\nint main() { D d; }', 'ABCD~D~C~B~A');
  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void f(int x = 10) { cout << x; }\n};\nclass B : public A {\npublic:\n  void f(int x = 20) { cout << x; }\n};\nint main() {\n  A* p = new B();\n  p->f();\n}', '10');
  add('oneword', 'What is the output?\n\nclass A {\n  int x, y;\npublic:\n  A(int a, int b) : x(a), y(b) { cout << "C" << x << y; }\n  A(const A& o) : x(o.x), y(o.y) { cout << "cp"; }\n  ~A() { cout << "~"; }\n};\nint main() {\n  A a(1, 2);\n  A b = a;\n  A c(3, 4);\n}', 'C12cpC34~~~');
  add('oneword', 'What is the output?\n\nclass Obj {\n  static int total;\npublic:\n  Obj() { total++; }\n  Obj(const Obj&) { total++; }\n  ~Obj() { total--; }\n  static int count() { return total; }\n};\nint Obj::total = 0;\nint main() {\n  Obj a;\n  {\n    Obj b;\n    Obj c = a;\n    cout << Obj::count();\n  }\n  cout << Obj::count();\n}', '31');
  add('oneword', 'What is the output?\n\nclass Num {\n  int v;\npublic:\n  Num(int x) : v(x) {}\n  operator std::string() { return "N" + to_string(v); }\n  operator int() { return v; }\n};\nint main() {\n  Num n(5);\n  cout << (int)n + 3;\n  cout << (string)n;\n}', '8N5');
  add('oneword', 'What is the output?\n\nclass Num {\n  int v;\npublic:\n  Num(int x) : v(x) {}\n  operator int() { return v; }\n  Num operator*(Num b) { return Num(v * b.v); }\n  friend ostream& operator<<(ostream& os, Num n) {\n    return os << n.v;\n  }\n};\nint main() {\n  Num a(3), b(4);\n  cout << a * b;\n  Num c(2);\n  cout << (int)(a * c);\n}', '126');
  add('oneword', 'What is the output?\n\nclass Policy {\npublic:\n  virtual void execute() = 0;\n  void run() { cout << "["; execute(); cout << "]"; }\n};\nclass Fast : public Policy {\npublic:\n  void execute() { cout << "fast"; }\n};\nclass Safe : public Policy {\npublic:\n  void execute() { cout << "safe"; }\n};\nint main() {\n  Policy* p = new Fast();\n  p->run();\n  p = new Safe();\n  p->run();\n}', '[fast][safe]');
  add('oneword', 'What is the output?\n\nstruct Base {\n  virtual int f() { return 1; }\n  int g() { return f() + 10; }\n};\nstruct Der : Base {\n  int f() { return 2; }\n};\nint main() {\n  Der d;\n  cout << d.g();\n}', '12');
  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual int compute(int x) { return x + 1; }\n};\nclass B : public A {\npublic:\n  int compute(int x) { return x * 2; }\n};\nclass C : public B {\n  int compute(int x) { return x * x; }\n};\nint main() {\n  A* p = new C();\n  B* q = new C();\n  cout << p->compute(3) << q->compute(3);\n}', '99');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  int x;\n  A(int v) : x(v) {}\n  virtual A* clone() { return new A(*this); }\n  virtual void show() { cout << "A" << x; }\n};\nclass B : public A {\npublic:\n  B(int v) : A(v) {}\n  A* clone() { return new B(*this); }\n  void show() { cout << "B" << x; }\n};\nint main() {\n  A* p = new B(7);\n  A* q = p->clone();\n  q->show();\n}', 'B7');
  add('oneword', 'What is the output?\n\nclass X {\n  static int alive;\npublic:\n  X() { alive++; }\n  X(const X&) { alive++; }\n  ~X() { alive--; }\n  static int count() { return alive; }\n};\nint X::alive = 0;\nint main() {\n  X* arr[3];\n  for(int i=0;i<3;i++) arr[i] = new X();\n  delete arr[1];\n  cout << X::count();\n}', '2');
  add('oneword', 'What is the output?\n\nclass Action {\npublic:\n  virtual void exec() = 0;\n  virtual ~Action() {}\n};\nclass Print : public Action {\n  const char* msg;\npublic:\n  Print(const char* s) : msg(s) {}\n  void exec() { cout << msg; }\n};\nint main() {\n  Action* cmds[3];\n  cmds[0] = new Print("Go");\n  cmds[1] = new Print("!");\n  cmds[2] = new Print("Win");\n  for(int i=0;i<3;i++) cmds[i]->exec();\n}', 'Go!Win');
  add('oneword', 'What is the output?\n\nstruct A {\n  virtual void f() { cout << "A"; }\n};\nstruct B : A {\n  void f() override { cout << "B"; }\n};\nstruct C : A {\n  void f() override { cout << "C"; }\n};\nstruct D : B, C {};\nint main() {\n  D d;\n  d.B::f();\n  d.C::f();\n}', 'BC');
  add('mcq', 'What is the output?\n\nclass A {\npublic:\n  A() { cout << "A"; }\n  virtual ~A() { cout << "~A"; }\n};\nclass B : public A {\npublic:\n  B() { cout << "B"; }\n  ~B() { cout << "~B"; }\n};\nclass C : public A {\npublic:\n  C() { cout << "C"; }\n  ~C() { cout << "~C"; }\n};\nclass D : public B {\n  C c;\npublic:\n  D() { cout << "D"; }\n  ~D() { cout << "~D"; }\n};\nint main() { D d; }', 'B) ABACD~D~C~A~B~A', ['A) ABCD~D~C~B~A', 'B) ABACD~D~C~A~B~A', 'C) ABDC~C~D~B~A', 'D) Compiler error']);

  add('oneword', 'What is the output?\n\nclass Guard {\n  const char* name;\npublic:\n  Guard(const char* n) : name(n) { cout << "+" << name; }\n  ~Guard() { cout << "-" << name; }\n};\nvoid test() {\n  Guard a("X");\n  Guard b("Y");\n}\nint main() {\n  test();\n  cout << "done";\n}', '+X+Y-Y-Xdone');
  add('oneword', 'What is the output?\n\nclass Stream {\n  int pos = 0;\n  string data;\npublic:\n  Stream(string s) : data(s) {}\n  char read() { return data[pos++]; }\n  bool eof() { return pos >= data.size(); }\n};\nint main() {\n  Stream s("abc");\n  while(!s.eof()) cout << s.read();\n}', 'abc');
  add('oneword', 'What is the output?\n\nclass Box {\n  int v;\npublic:\n  Box(int x) : v(x) { cout << "B" << v; }\n  Box(const Box& o) : v(o.v) { cout << "C"; }\n};\nBox make(int x) { return Box(x); }\nint main() {\n  Box b = make(42);\n  cout << "!";\n}', 'B42!');
  add('oneword', 'What is the output?\n\nclass Bits {\n  uint8_t b = 0;\npublic:\n  void set(int i) { b |= (1 << i); }\n  bool get(int i) { return (b >> i) & 1; }\n};\nint main() {\n  Bits b;\n  b.set(2);\n  b.set(5);\n  cout << b.get(2) << b.get(5) << b.get(1);\n}', '110');
  add('oneword', 'What is the output?\n\nclass Derived;\nclass Base {\npublic:\n  virtual Derived* create() = 0;\n  virtual void show() = 0;\n};\nclass Derived : public Base {\npublic:\n  Derived* create() { return new Derived(); }\n  void show() { cout << "D"; }\n};\nint main() {\n  Base* p = new Derived();\n  Base* q = p->create();\n  q->show();\n}', 'D');
  add('oneword', 'What is the output?\n\nstruct Vec2 {\n  float x, y;\n  Vec2(float a, float b) : x(a), y(b) {}\n  Vec2 operator+(Vec2 v) { return {x+v.x, y+v.y}; }\n  friend ostream& operator<<(ostream& os, Vec2 v) {\n    return os << v.x << "," << v.y;\n  }\n};\nint main() {\n  Vec2 a(1,2), b(3,4);\n  cout << a+b;\n}', '4,6');

  add('mcq', 'What is the output?\n\nclass Scope {\n  string name;\npublic:\n  Scope(string n) : name(n) { cout << "Enter:" << n; }\n  ~Scope() { cout << "Exit:" << name; }\n};\nint main() {\n  Scope a("main");\n  {\n    Scope b("block");\n  }\n  cout << "mid";\n}', 'B) Enter:mainEnter:blockExit:blockmidExit:main', ['A) Enter:mainmidExit:main', 'B) Enter:mainEnter:blockExit:blockmidExit:main', 'C) Enter:blockExit:blockEnter:mainExit:main', 'D) Compiler error']);
  add('oneword', 'What is the output?\n\nclass Str {\n  char* data;\n  int len;\npublic:\n  Str(const char* s) {\n    len = 0;\n    while(s[len]) len++;\n    data = new char[len+1];\n    for(int i=0;i<=len;i++) data[i] = s[i];\n    cout << "S";\n  }\n  Str(const Str& o) {\n    len = o.len;\n    data = new char[len+1];\n    for(int i=0;i<=len;i++) data[i] = o.data[i];\n    cout << "C";\n  }\n  ~Str() { delete[] data; cout << "~"; }\n  void print() { cout << data; }\n};\nint main() {\n  Str a("Hi");\n  Str b = a;\n  b.print();\n}', 'SCHi~~');
  add('oneword', 'What is the output?\n\nclass Counter {\n  int n;\npublic:\n  Counter(int v = 0) : n(v) {}\n  Counter& operator++() { ++n; return *this; }\n  Counter operator++(int) { Counter tmp = *this; ++n; return tmp; }\n  int val() const { return n; }\n};\nint main() {\n  Counter c(5);\n  Counter a = c++;\n  ++c;\n  cout << a.val() << c.val();\n}', '57');
  add('oneword', 'What is the output?\n\nclass ID {\n  static int next;\n  int id;\npublic:\n  ID() : id(next++) { cout << id; }\n  ID(const ID& o) : id(next++) { cout << id; }\n  ~ID() { cout << "~" << id; }\n};\nint ID::next = 1;\nint main() {\n  ID a;\n  ID b;\n  ID c = a;\n  cout << "|";\n}', '123|~3~2~1');
  add('oneword', 'What is the output?\n\nclass FSM {\n  enum State { IDLE, RUNNING, DONE };\n  State s = IDLE;\npublic:\n  void start() {\n    if(s == IDLE) { s = RUNNING; cout << "start"; }\n    else cout << "err";\n  }\n  void finish() {\n    if(s == RUNNING) { s = DONE; cout << "done"; }\n    else cout << "err";\n  }\n};\nint main() {\n  FSM m;\n  m.start();\n  m.start();\n  m.finish();\n}', 'starterrdone');

  add('oneword', 'What is the output?\n\nstruct Tag { string name; };\nstruct A : Tag {\n  A() { name = "A"; }\n  virtual string greet() { return "Hi" + name; }\n};\nstruct B : A {\n  B() { name = "B"; }\n  string greet() { return "Hey" + name; }\n};\nint main() {\n  A* p = new B();\n  cout << p->greet();\n}', 'HeyB');
  add('oneword', 'What is the output?\n\nclass Logger {\n  const char* tag;\npublic:\n  Logger(const char* t) : tag(t) { cout << ">" << tag; }\n  ~Logger() { cout << "<" << tag; }\n};\nbool validate(int x) { return x > 0; }\nvoid process(int x) {\n  Logger l("P");\n  if(!validate(x)) return;\n  cout << x;\n}\nint main() {\n  process(5);\n  process(-1);\n  cout << "end";\n}', '>P5<P>P<Pend');
  add('oneword', 'What is the output?\n\nclass Arr {\n  int data[5];\n  int size;\npublic:\n  Arr() : size(0) {}\n  void add(int v) { data[size++] = v; }\n  void doubleAll() {\n    for(int i=0; i<size; i++) data[i] *= 2;\n  }\n  void print() {\n    for(int i=0; i<size; i++) cout << data[i];\n  }\n};\nint main() {\n  Arr a;\n  a.add(1); a.add(2); a.add(3);\n  a.doubleAll();\n  a.print();\n}', '246');
  add('oneword', 'What is the output?\n\nstruct ID {\n  static int next;\n  int id;\n  ID() : id(next++) {}\n};\nint ID::next = 1;\nint main() {\n  ID a, b, c;\n  cout << b.id;\n}', '2');
  add('oneword', 'What is the output?\n\nstruct Lazy {\n  mutable int cache = -1;\n  int heavy() const {\n    if(cache < 0) { cache = 42; cout << "calc"; }\n    return cache;\n  }\n};\nint main() {\n  const Lazy l;\n  cout << l.heavy();\n  cout << l.heavy();\n}', 'calc4242');

  add('oneword', 'What is the output?\n\nclass A {\n  int x;\npublic:\n  A(int v) : x(v) {}\n  friend class B;\n};\nclass B {\n  int y;\npublic:\n  B(int v) : y(v) {}\n  int sum(const A& a) { return a.x + y; }\n};\nint main() {\n  A a(10);\n  B b(20);\n  cout << b.sum(a);\n}', '30');
  add('oneword', 'What is the output?\n\nclass Buffer {\n  int* data;\n  int sz;\npublic:\n  Buffer(int n) : sz(n) {\n    data = new int[n];\n    cout << "+";\n  }\n  Buffer(const Buffer& o) : sz(o.sz) {\n    data = new int[sz];\n    for(int i=0;i<sz;i++) data[i]=o.data[i];\n    cout << "c";\n  }\n  ~Buffer() { delete[] data; cout << "-"; }\n  void set(int i, int v) { data[i] = v; }\n  int get(int i) { return data[i]; }\n};\nint main() {\n  Buffer a(3);\n  a.set(0, 7);\n  Buffer b = a;\n  cout << b.get(0);\n}', '+c7--');
  add('oneword', 'What is the output?\n\nstruct Circle;\nstruct Canvas {\n  void draw(Circle& c);\n};\nstruct Circle {\n  int r;\n  Circle(int v) : r(v) {}\n  friend void Canvas::draw(Circle& c);\n};\nvoid Canvas::draw(Circle& c) {\n  cout << "r=" << c.r;\n}\nint main() {\n  Canvas cv;\n  Circle c(5);\n  cv.draw(c);\n}', 'r=5');
  add('oneword', 'What is the output?\n\nclass Timer {\n  int ticks;\n  const char* label;\npublic:\n  Timer(const char* l, int t) : label(l), ticks(t) {}\n  void countdown() {\n    while(ticks > 0) {\n      cout << label << ticks;\n      ticks--;\n    }\n    cout << label << "!";\n  }\n};\nint main() {\n  Timer t("T", 3);\n  t.countdown();\n}', 'T3T2T1T!');
  add('oneword', 'What is the output?\n\nstruct Chain {\n  int v;\n  Chain(int x) : v(x) {}\n  Chain add(int n) const { return Chain(v + n); }\n  Chain mul(int n) const { return Chain(v * n); }\n  void out() const { cout << v; }\n};\nint main() {\n  Chain(2).add(3).mul(4).out();\n}', '20');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  A() { cout << "A"; }\n  ~A() { cout << "~A"; }\n};\nclass B {\n  A a;\n  A b;\npublic:\n  B() { cout << "B"; }\n  ~B() { cout << "~B"; }\n};\nint main() {\n  B obj;\n  cout << "|";\n}', 'AAB|~B~A~A');
  add('oneword', 'What is the output?\n\nclass Node {\n  int v;\n  Node* next;\npublic:\n  Node(int x, Node* n = nullptr) : v(x), next(n) {}\n  Node(const Node& o) : v(o.v), next(nullptr) {\n    if(o.next) next = new Node(*o.next);\n  }\n  ~Node() { delete next; }\n  void print() {\n    cout << v;\n    if(next) next->print();\n  }\n};\nint main() {\n  Node* head = new Node(1, new Node(2, new Node(3)));\n  Node copy = *head;\n  copy.print();\n  delete head;\n}', '123');
  add('oneword', 'What is the output?\n\nstruct Poly {\n  string name;\n  Poly(string n) : name(n) {}\n  virtual string id() { return name; }\n};\nstruct Sub : Poly {\n  Sub(string n) : Poly(n + "!") {}\n  string id() { return "[" + name + "]"; }\n};\nint main() {\n  Poly* p = new Sub("X");\n  cout << p->id();\n}', '[X!]');
  add('oneword', 'What is the output?\n\nclass Matrix {\n  int data[2][2];\npublic:\n  Matrix(int a, int b, int c, int d) {\n    data[0][0]=a; data[0][1]=b; data[1][0]=c; data[1][1]=d;\n  }\n  Matrix operator+(const Matrix& m) const {\n    return Matrix(data[0][0]+m.data[0][0], data[0][1]+m.data[0][1],\n                  data[1][0]+m.data[1][0], data[1][1]+m.data[1][1]);\n  }\n  int trace() const { return data[0][0] + data[1][1]; }\n};\nint main() {\n  Matrix a(1,2,3,4), b(5,6,7,8);\n  cout << (a+b).trace();\n}', '18');
  add('oneword', 'What is the output?\n\nstruct Watch {\n  int t;\n  Watch(int s) : t(s) {}\n  Watch& tick() { --t; return *this; }\n  bool expired() { return t <= 0; }\n};\nint main() {\n  Watch w(3);\n  while(!w.expired()) w.tick();\n  cout << w.t;\n}', '0');

  add('oneword', 'What is the output?\n\nclass Pair {\n  int a, b;\npublic:\n  Pair(int x, int y) : a(x), b(y) {}\n  Pair(const Pair& o) : a(o.b), b(o.a) { cout << "sw"; }\n  void show() const { cout << a << "," << b; }\n};\nint main() {\n  Pair p(1, 2);\n  Pair q = p;\n  q.show();\n}', 'sw2,1');
  add('oneword', 'What is the output?\n\nstruct Token {\n  string s;\n  Token(string x) : s(x) {}\n  Token operator+(Token t) { return Token(s + t.s); }\n};\nostream& operator<<(ostream& os, Token t) { return os << t.s; }\nint main() {\n  cout << Token("ab") + Token("cd") + Token("ef");\n}', 'abcdef');

  // ── 20 ADDITIONAL LEVEL 9 QUESTIONS (IDs 951–970) ──

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  A() { cout << "A"; }\n  virtual ~A() { cout << "a"; }\n};\nclass B : public A {\npublic:\n  B() { cout << "B"; }\n  ~B() { cout << "b"; }\n};\nvoid process() {\n  B arr[2];\n  cout << "|";\n}\nint main() {\n  process();\n  cout << "end";\n}', 'ABAB|babaend');

  add('oneword', 'What is the output?\n\nclass A {\nprotected:\n  int x;\npublic:\n  A(int v) : x(v) {}\n  virtual A& operator++() {\n    x += 1;\n    return *this;\n  }\n  void show() { cout << x; }\n};\nclass B : public A {\npublic:\n  B(int v) : A(v) {}\n  B& operator++() {\n    x += 10;\n    return static_cast<B&>(*this);\n  }\n};\nint main() {\n  A* p = new B(5);\n  ++(*p);\n  p->show();\n}', '15');

  add('mcq', 'What is the output?\n\nclass Obj {\n  static int count;\n  int id;\npublic:\n  Obj() : id(++count) { cout << "+" << id; }\n  Obj(const Obj& o) : id(++count) { cout << "c" << id; }\n  ~Obj() { cout << "-" << id; }\n};\nint Obj::count = 0;\nvoid f(Obj o) { cout << "."; }\nint main() {\n  Obj a;\n  f(a);\n  cout << "end";\n}', 'A) +1c2.-2end-1', ['A) +1c2.-2end-1', 'B) +1.end-1', 'C) +1c2.end-2-1', 'D) +1c2.-2-1end']);

  add('mcq', 'Find the bug:\n\nclass Smart {\n  int* ptr;\npublic:\n  Smart(int v) : ptr(new int(v)) {}\n  Smart(Smart&& o) : ptr(o.ptr) { o.ptr = nullptr; }\n  Smart& operator=(Smart&& o) {\n    ptr = o.ptr;\n    o.ptr = nullptr;\n    return *this;\n  }\n  ~Smart() { delete ptr; }\n};', 'B) Move assignment does not delete the existing ptr before taking ownership — memory leak', ['A) Move constructor is wrong', 'B) Move assignment does not delete the existing ptr before taking ownership — memory leak', 'C) Should use smart pointers instead', 'D) No bug']);

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void f() { cout << "A"; }\n  void g() { f(); }\n  ~A() { g(); }\n};\nclass B : public A {\npublic:\n  void f() { cout << "B"; }\n};\nint main() {\n  B b;\n  b.g();\n  cout << "|";\n}', 'B|A');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  A() { cout << 1; }\n  A(const A&) { cout << 2; }\n  A& operator=(const A&) { cout << 3; return *this; }\n  ~A() { cout << 4; }\n};\nint main() {\n  A a;\n  A b(a);\n  A c;\n  c = a;\n}', '121344');

  add('oneword', 'What is the output?\n\nclass Base {\npublic:\n  int x;\n  Base(int v) : x(v) {}\n  virtual int compute() { return x * 2; }\n};\nclass D1 : virtual public Base {\npublic:\n  D1(int v) : Base(v) {}\n  int compute() { return x * 3; }\n};\nclass D2 : virtual public Base {\npublic:\n  D2(int v) : Base(v) {}\n  int compute() { return x * 5; }\n};\nclass Bottom : public D1, public D2 {\npublic:\n  Bottom(int v) : Base(v), D1(v), D2(v) {}\n  int compute() { return D1::compute() + D2::compute(); }\n};\nint main() {\n  Base* p = new Bottom(4);\n  cout << p->compute();\n}', '32');

  add('mcq', 'Find the error:\n\nclass Iter {\n  int* arr;\n  int pos;\n  int sz;\npublic:\n  Iter(int* a, int n) : arr(a), pos(0), sz(n) {}\n  int& operator*() { return arr[pos]; }\n  Iter& operator++() { pos++; return *this; }\n  bool operator!=(const Iter& o) { return pos != o.pos; }\n};\nint main() {\n  int data[] = {10, 20, 30};\n  Iter begin(data, 3);\n  Iter end(data, 3);\n  while(begin != end) {\n    cout << *begin << " ";\n    ++begin;\n  }\n}', 'B) end has pos=0 same as begin — loop never executes because begin == end from the start', ['A) operator* should return const ref', 'B) end has pos=0 same as begin — loop never executes because begin == end from the start', 'C) operator!= should compare arr pointers too', 'D) No bug — prints 10 20 30']);

  add('oneword', 'What is the output?\n\nclass Resource {\npublic:\n  Resource() { cout << "R"; }\n  ~Resource() { cout << "~R"; }\n};\nclass Owner {\n  Resource* r;\npublic:\n  Owner() : r(new Resource()) { cout << "O"; }\n  Owner(const Owner& o) : r(new Resource()) { cout << "cO"; }\n  ~Owner() { delete r; cout << "~O"; }\n};\nint main() {\n  Owner a;\n  {\n    Owner b = a;\n  }\n  cout << "|";\n}', 'RORcO~R~O|~R~O');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void speak() { cout << "A"; }\n};\nclass B : public A {\npublic:\n  void speak() { cout << "B"; }\n};\nclass C : public A {\npublic:\n  void speak() { cout << "C"; }\n};\nint main() {\n  A* arr[] = { new B(), new C(), new B() };\n  for(int i = 0; i < 3; i++) arr[i]->speak();\n}', 'BCB');

  add('oneword', 'What is the output?\n\nclass Frac {\n  int n, d;\npublic:\n  Frac(int num, int den = 1) : n(num), d(den) {}\n  Frac operator*(const Frac& o) const {\n    return Frac(n * o.n, d * o.d);\n  }\n  void show() const { cout << n << "/" << d; }\n};\nint main() {\n  Frac a(2, 3);\n  Frac b(3, 4);\n  (a * b).show();\n}', '6/12');

  add('mcq', 'What is the output?\n\nclass X {\npublic:\n  X() { cout << "X"; }\n  X(const X&) { cout << "cX"; }\n  ~X() { cout << "~X"; }\n};\nclass Y {\n  X x1, x2;\npublic:\n  Y() { cout << "Y"; }\n  Y(const Y& o) : x2(o.x2) { cout << "cY"; }\n  ~Y() { cout << "~Y"; }\n};\nint main() {\n  Y a;\n  Y b = a;\n}', 'B) XXYXcXcY~Y~X~X~Y~X~X', ['A) XXYcXcXcY~Y~X~X~Y~X~X', 'B) XXYXcXcY~Y~X~X~Y~X~X', 'C) XXYcXcY~Y~X~X~Y~X~X', 'D) Compiler error']);

  add('mcq', 'Find the bug:\n\nclass Pool {\n  int* block;\n  bool* used;\n  int cap;\npublic:\n  Pool(int n) : cap(n) {\n    block = new int[n];\n    used = new bool[n];\n    for(int i = 0; i < n; i++) used[i] = false;\n  }\n  int* alloc() {\n    for(int i = 0; i < cap; i++)\n      if(!used[i]) { used[i] = true; return &block[i]; }\n    return nullptr;\n  }\n  void free(int* p) {\n    int idx = p - block;\n    used[idx] = false;\n  }\n  ~Pool() { delete[] block; }\n};', 'C) Destructor deletes block but never deletes the used array — memory leak', ['A) free() pointer arithmetic is unsafe', 'B) alloc() should throw instead of returning nullptr', 'C) Destructor deletes block but never deletes the used array — memory leak', 'D) No bug']);

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void f() const { cout << "Ac"; }\n  virtual void f() { cout << "A"; }\n};\nclass B : public A {\npublic:\n  void f() const { cout << "Bc"; }\n  void f() { cout << "B"; }\n};\nint main() {\n  const A* p = new B();\n  p->f();\n  A* q = new B();\n  q->f();\n}', 'BcB');

  add('oneword', 'What is the output?\n\nclass Guard {\npublic:\n  Guard(const char* n) { cout << n << "+"; }\n  ~Guard() { cout << "-"; }\n};\nvoid risky() {\n  Guard g1("a");\n  Guard g2("b");\n  throw 42;\n  Guard g3("c");\n}\nint main() {\n  try {\n    risky();\n  } catch(int) {\n    cout << "caught";\n  }\n}', 'a+b+--caught');

  add('oneword', 'What is the output?\n\nstruct A {\n  int x;\n  A(int v) : x(v) {}\n  virtual A& add(int v) { x += v; return *this; }\n};\nstruct B : A {\n  B(int v) : A(v) {}\n  B& add(int v) { x += v * 2; return static_cast<B&>(*this); }\n};\nint main() {\n  B b(10);\n  A& ref = b;\n  ref.add(5).add(3);\n  cout << b.x;\n}', '26');

  add('oneword', 'What is the output?\n\nclass Lazy {\n  mutable int cache;\n  mutable bool valid;\n  int data;\npublic:\n  Lazy(int d) : data(d), cache(0), valid(false) {}\n  int compute() const {\n    if(!valid) {\n      cache = data * data;\n      valid = true;\n    }\n    return cache;\n  }\n};\nint main() {\n  const Lazy l(7);\n  cout << l.compute() << l.compute();\n}', '4949');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void f() { cout << "A"; g(); }\n  virtual void g() { cout << "1"; }\n};\nclass B : public A {\npublic:\n  void f() { cout << "B"; A::f(); }\n  void g() { cout << "2"; }\n};\nint main() {\n  A* p = new B();\n  p->f();\n}', 'BA2');

  add('mcq', 'What is the output?\n\nclass Cnt {\n  static int total;\n  int id;\npublic:\n  Cnt() : id(total++) {}\n  Cnt(const Cnt&) : id(total++) {}\n  static int getTotal() { return total; }\n  int getId() { return id; }\n};\nint Cnt::total = 0;\nCnt make() { Cnt c; return c; }\nint main() {\n  Cnt a = make();\n  Cnt b = a;\n  cout << Cnt::getTotal();\n}', 'C) Output depends on copy elision — 2 or 3', ['A) 1', 'B) 2', 'C) Output depends on copy elision — 2 or 3', 'D) 4']);

  add('oneword', 'What is the output?\n\nclass Engine {\n  int hp;\npublic:\n  Engine(int h) : hp(h) { cout << "E" << hp; }\n  ~Engine() { cout << "~E"; }\n};\nclass Car {\n  Engine e1;\n  Engine e2;\npublic:\n  Car() : e2(200), e1(100) { cout << "C"; }\n  ~Car() { cout << "~C"; }\n};\nint main() {\n  Car c;\n}', 'E100E200C~C~E~E');

  // ── 30 MORE LEVEL 9 QUESTIONS (IDs 971–1000) ──

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void run() { cout << "A"; step(); }\n  virtual void step() { cout << "1"; }\n  virtual ~A() {}\n};\nclass B : public A {\npublic:\n  void step() { cout << "2"; }\n};\nclass C : public B {\npublic:\n  void run() { A::run(); cout << "+"; step(); }\n  void step() { cout << "3"; }\n};\nint main() {\n  A* p = new C();\n  p->run();\n}', 'A3+3');

  add('oneword', 'What is the output?\n\nclass Ref {\n  int& r;\npublic:\n  Ref(int& x) : r(x) {}\n  void inc() { r++; }\n  int get() const { return r; }\n};\nint main() {\n  int a = 10;\n  Ref r1(a);\n  Ref r2(a);\n  r1.inc();\n  r2.inc();\n  cout << a << r1.get() << r2.get();\n}', '121212');

  add('oneword', 'What is the output?\n\nclass Base {\nprotected:\n  int x;\npublic:\n  Base(int v) : x(v) {}\n  virtual void transform() { x *= 2; }\n  void apply() { transform(); cout << x; }\n};\nclass Der : public Base {\npublic:\n  Der(int v) : Base(v) {}\n  void transform() { x += 100; }\n};\nint main() {\n  Base* p = new Der(5);\n  p->apply();\n  p->apply();\n}', '105205');

  add('mcq', 'What is the output?\n\nclass A {\npublic:\n  A() { cout << "A"; }\n  A(const A&) { cout << "cA"; }\n  ~A() { cout << "~A"; }\n};\nclass B {\n  A a1, a2;\npublic:\n  B() { cout << "B"; }\n  B(const B& o) : a1(o.a1) { cout << "cB"; }\n  ~B() { cout << "~B"; }\n};\nint main() {\n  B b;\n  B b2 = b;\n  cout << "|";\n}', 'B) AABcAAcB|~B~A~A~B~A~A', ['A) AABcAcAcB|~B~A~A~B~A~A', 'B) AABcAAcB|~B~A~A~B~A~A', 'C) AABcAcB|~B~A~A~B~A~A', 'D) AABcB|~B~A~A~B~A~A']);

  add('oneword', 'What is the output?\n\nclass RingBuf {\n  int data[4];\n  int head = 0, tail = 0, count = 0;\npublic:\n  void push(int v) { data[tail] = v; tail = (tail+1)%4; count++; }\n  int pop() { int v = data[head]; head = (head+1)%4; count--; return v; }\n};\nint main() {\n  RingBuf r;\n  r.push(10); r.push(20); r.push(30);\n  cout << r.pop();\n  r.push(40); r.push(50);\n  cout << r.pop() << r.pop();\n}', '102030');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  virtual void f() { cout << "A"; }\n  virtual ~A() { cout << "~A"; }\n};\nclass B : public A {\npublic:\n  void f() { cout << "B"; }\n  ~B() { cout << "~B"; }\n};\nint main() {\n  A* arr[] = { new A(), new B(), new A() };\n  for(int i=0;i<3;i++) arr[i]->f();\n  cout << "|";\n  for(int i=2;i>=0;i--) delete arr[i];\n}', 'ABA|~A~B~A~A');

  add('mcq', 'Find the bug:\n\nclass Array {\n  int* data;\n  int size;\npublic:\n  Array(int n) : size(n), data(new int[n]()) {}\n  Array(const Array& o) : size(o.size), data(new int[o.size]) {\n    for(int i=0;i<size;i++) data[i]=o.data[i];\n  }\n  ~Array() { delete[] data; }\n  int& operator[](int i) { return data[i]; }\n};', 'C) Missing operator= — if assigned, the old data leaks and both objects share the same pointer after default memberwise copy', ['A) Constructor should use new int[n] not new int[n]()', 'B) Copy constructor is incorrect', 'C) Missing operator= — if assigned, the old data leaks and both objects share the same pointer after default memberwise copy', 'D) No bug']);

  add('mcq', 'What is the output?\n\nstruct Event {\n  virtual string type() = 0;\n  virtual ~Event() {}\n};\nstruct Click : Event { string type() { return "click"; } };\nstruct Key : Event { string type() { return "key"; } };\nstruct Scroll : Event { string type() { return "scroll"; } };\nint main() {\n  Event* events[] = { new Click(), new Key(), new Scroll(), new Click() };\n  for(int i=0;i<4;i++) cout << events[i]->type() << " ";\n}', 'A) click key scroll click ', ['A) click key scroll click ', 'B) Event Event Event Event ', 'C) Compiler error', 'D) click key scroll ']);

  add('oneword', 'What is the output?\n\nclass Wrapper {\n  int* p;\npublic:\n  explicit Wrapper(int v) : p(new int(v)) {}\n  Wrapper(Wrapper&& o) noexcept : p(o.p) { o.p = nullptr; }\n  ~Wrapper() { if(p) { cout << *p; delete p; } else { cout << "N"; } }\n};\nint main() {\n  Wrapper a(5);\n  Wrapper b(static_cast<Wrapper&&>(a));\n  cout << "|";\n}', '|5N');

  add('oneword', 'What is the output?\n\nclass Table {\n  int rows[3][3] = {};\npublic:\n  void set(int r, int c, int v) { rows[r][c] = v; }\n  int rowSum(int r) {\n    int s = 0;\n    for(int c=0;c<3;c++) s += rows[r][c];\n    return s;\n  }\n  int diagSum() {\n    int s = 0;\n    for(int i=0;i<3;i++) s += rows[i][i];\n    return s;\n  }\n};\nint main() {\n  Table t;\n  t.set(0,0,1); t.set(0,1,2); t.set(0,2,3);\n  t.set(1,1,5);\n  t.set(2,2,9);\n  cout << t.rowSum(0) << t.diagSum();\n}', '615');

  add('mcq', 'What is the output?\n\nclass A {\npublic:\n  virtual void f() { cout << "A::f "; }\n  void g() { cout << "A::g "; f(); }\n};\nclass B : public A {\npublic:\n  void f() { cout << "B::f "; }\n  void g() { cout << "B::g "; A::g(); }\n};\nint main() {\n  B b;\n  A* p = &b;\n  p->g();\n  cout << "| ";\n  b.g();\n}', 'A) A::g B::f | B::g A::g B::f ', ['A) A::g B::f | B::g A::g B::f ', 'B) A::g A::f | B::g A::g A::f ', 'C) B::g A::g B::f | B::g A::g B::f ', 'D) A::g B::f | A::g B::f ']);

  add('oneword', 'What is the output?\n\nclass Token {\n  char c;\npublic:\n  Token(char ch) : c(ch) { cout << c; }\n  Token(const Token& o) : c(o.c + 1) { cout << c; }\n  ~Token() { cout << "~" << c; }\n};\nint main() {\n  Token t(\'A\');\n  Token u = t;\n  Token v = u;\n  cout << "|";\n}', 'ABC|~C~B~A');

  add('oneword', 'What is the output?\n\nclass BitSet {\n  unsigned int bits = 0;\npublic:\n  BitSet& set(int pos) { bits |= (1u << pos); return *this; }\n  BitSet& clear(int pos) { bits &= ~(1u << pos); return *this; }\n  bool test(int pos) const { return (bits >> pos) & 1; }\n  int count() const {\n    unsigned int b = bits;\n    int c = 0;\n    while(b) { c += b & 1; b >>= 1; }\n    return c;\n  }\n};\nint main() {\n  BitSet bs;\n  bs.set(0).set(3).set(7).set(3).clear(0);\n  cout << bs.count() << bs.test(0) << bs.test(3);\n}', '201');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  int x;\n  A(int v) : x(v) { cout << "A" << x; }\n  virtual ~A() { cout << "~A"; }\n};\nclass B : public A {\npublic:\n  B(int v) : A(v + 1) { x += 10; cout << "B" << x; }\n  ~B() { cout << "~B"; }\n};\nint main() {\n  A* p = new B(5);\n  cout << p->x;\n  delete p;\n}', 'A6B1616~B~A');

  add('mcq', 'What is the output?\n\nclass Logger {\n  static int depth;\npublic:\n  Logger(const char* fn) {\n    for(int i=0;i<depth;i++) cout << " ";\n    cout << ">" << fn << "\\n";\n    depth++;\n  }\n  ~Logger() {\n    depth--;\n    for(int i=0;i<depth;i++) cout << " ";\n    cout << "<\\n";\n  }\n};\nint Logger::depth = 0;\nvoid c() { Logger l("c"); }\nvoid b() { Logger l("b"); c(); }\nvoid a() { Logger l("a"); b(); }\nint main() { a(); }', 'A) >a\\n >b\\n  >c\\n  <\\n <\\n<\\n', ['A) >a\\n >b\\n  >c\\n  <\\n <\\n<\\n', 'B) >a\\n>b\\n>c\\n<\\n<\\n<\\n', 'C) >c\\n<\\n>b\\n<\\n>a\\n<\\n', 'D) Compiler error']);

  add('oneword', 'What is the output?\n\nclass Dbl {\n  int v;\npublic:\n  Dbl(int x) : v(x) {}\n  Dbl operator+(const Dbl& o) const { return Dbl(v + o.v); }\n  Dbl operator-(const Dbl& o) const { return Dbl(v - o.v); }\n  Dbl operator-() const { return Dbl(-v); }\n  friend ostream& operator<<(ostream& os, Dbl d) { return os << d.v; }\n};\nint main() {\n  Dbl a(7), b(3);\n  cout << -(a - b);\n  cout << (-a) + b;\n}', '-4-4');

  add('oneword', 'What is the output?\n\nclass Queue {\n  int data[10];\n  int front = 0, back = 0;\npublic:\n  void enqueue(int v) { data[back++] = v; }\n  int dequeue() { return data[front++]; }\n  bool empty() { return front == back; }\n};\nint main() {\n  Queue q;\n  q.enqueue(1); q.enqueue(2); q.enqueue(3);\n  cout << q.dequeue();\n  q.enqueue(4);\n  while(!q.empty()) cout << q.dequeue();\n}', '1234');

  add('oneword', 'What is the output?\n\nclass Shape {\npublic:\n  virtual double area() = 0;\n  virtual ~Shape() {}\n  bool biggerThan(Shape& other) { return area() > other.area(); }\n};\nclass Rect : public Shape {\n  int w, h;\npublic:\n  Rect(int w, int h) : w(w), h(h) {}\n  double area() { return w * h; }\n};\nclass Tri : public Shape {\n  int b, h;\npublic:\n  Tri(int b, int h) : b(b), h(h) {}\n  double area() { return 0.5 * b * h; }\n};\nint main() {\n  Rect r(4, 5);\n  Tri t(8, 5);\n  cout << r.biggerThan(t) << t.biggerThan(r);\n}', '00');

  add('mcq', 'Find the bug:\n\nclass Str {\n  char* buf;\n  int len;\npublic:\n  Str(const char* s) {\n    len = strlen(s);\n    buf = new char[len + 1];\n    strcpy(buf, s);\n  }\n  Str operator+(const Str& o) const {\n    char* tmp = new char[len + o.len + 1];\n    strcpy(tmp, buf);\n    strcat(tmp, o.buf);\n    Str result(tmp);\n    return result;\n  }\n  ~Str() { delete[] buf; }\n};', 'B) operator+ allocates tmp, passes it to Str(const char*) which allocates again — tmp is never freed (memory leak)', ['A) strcpy should be strncpy', 'B) operator+ allocates tmp, passes it to Str(const char*) which allocates again — tmp is never freed (memory leak)', 'C) Missing copy constructor', 'D) No bug']);

  add('oneword', 'What is the output?\n\nclass A {\n  int v;\npublic:\n  A(int x) : v(x) {}\n  A operator+(int n) { return A(v + n); }\n  friend A operator+(int n, const A& a) { return A(n + a.v); }\n  friend ostream& operator<<(ostream& os, const A& a) { return os << a.v; }\n};\nint main() {\n  A a(10);\n  cout << (a + 5);\n  cout << (3 + a);\n}', '1513');

  add('oneword', 'What is the output?\n\nint global = 0;\nclass Inc {\npublic:\n  Inc() { global++; }\n  Inc(const Inc&) { global += 10; }\n  ~Inc() { global += 100; }\n};\nvoid foo(Inc i) { }\nint main() {\n  Inc a;\n  foo(a);\n  cout << global;\n}', '111');

  add('oneword', 'What is the output?\n\nclass Base {\npublic:\n  virtual void describe() { cout << "Base"; }\n  void identify() { cout << "["; describe(); cout << "]"; }\n};\nclass Mid : public Base {\npublic:\n  void describe() { cout << "Mid"; }\n};\nclass Top : public Mid {\npublic:\n  void describe() { cout << "Top"; }\n};\nint main() {\n  Top t;\n  Base& ref = t;\n  ref.identify();\n  Mid* pm = &t;\n  pm->identify();\n}', '[Top][Top]');

  add('mcq', 'What is the output?\n\nclass Auto {\n  static int next;\n  int id;\n  const char* label;\npublic:\n  Auto(const char* l) : id(next++), label(l) { cout << label << id << "+"; }\n  ~Auto() { cout << label << id << "-"; }\n};\nint Auto::next = 0;\nvoid step() {\n  Auto a("s");\n}\nint main() {\n  Auto a("m");\n  step();\n  step();\n  cout << "end";\n}', 'A) m0+s1+s1-s2+s2-end m0-', ['A) m0+s1+s1-s2+s2-endm0-', 'B) m0+s1+s2+s2-s1-endm0-', 'C) m0+s1+s1-s1+s1-endm0-', 'D) s0+s0-s1+s1-m2+endm2-']);

  add('oneword', 'What is the output?\n\nclass Version {\n  int major, minor, patch;\npublic:\n  Version(int a, int b, int c) : major(a), minor(b), patch(c) {}\n  bool operator>(const Version& o) const {\n    if(major != o.major) return major > o.major;\n    if(minor != o.minor) return minor > o.minor;\n    return patch > o.patch;\n  }\n  bool operator==(const Version& o) const {\n    return major == o.major && minor == o.minor && patch == o.patch;\n  }\n};\nint main() {\n  Version a(2,1,3), b(2,1,3), c(2,2,0);\n  cout << (a > b) << (a == b) << (c > a);\n}', '011');

  add('oneword', 'What is the output?\n\nstruct A {\n  virtual void f() { cout << "Af"; }\n  virtual ~A() {}\n};\nstruct B : A {\n  void f() final { cout << "Bf"; }\n};\nstruct C : B {\n  // void f() { cout << "Cf"; } // Would be compile error due to final\n  void g() { cout << "Cg"; }\n};\nint main() {\n  A* p = new C();\n  p->f();\n  static_cast<C*>(p)->g();\n}', 'BfCg');

  add('oneword', 'What is the output?\n\nclass Safe {\n  int* data;\n  int sz;\npublic:\n  Safe(int n) : sz(n), data(new int[n]()) {}\n  Safe(const Safe& o) : sz(o.sz), data(new int[o.sz]) {\n    for(int i=0;i<sz;i++) data[i] = o.data[i];\n  }\n  Safe& operator=(const Safe& o) {\n    if(this == &o) return *this;\n    delete[] data;\n    sz = o.sz;\n    data = new int[sz];\n    for(int i=0;i<sz;i++) data[i] = o.data[i];\n    return *this;\n  }\n  ~Safe() { delete[] data; }\n  void set(int i, int v) { data[i] = v; }\n  int get(int i) const { return data[i]; }\n};\nint main() {\n  Safe a(3);\n  a.set(0, 42);\n  Safe b = a;\n  b.set(0, 99);\n  cout << a.get(0) << b.get(0);\n}', '4299');

  add('oneword', 'What is the output?\n\nclass Cache {\n  mutable int hits = 0;\n  int val;\npublic:\n  Cache(int v) : val(v) {}\n  int get() const { hits++; return val; }\n  int getHits() const { return hits; }\n};\nint main() {\n  const Cache c(7);\n  c.get(); c.get(); c.get();\n  cout << c.getHits() << c.get();\n}', '37');

  add('oneword', 'What is the output?\n\nclass A {\npublic:\n  int x;\n  A(int v) : x(v) {}\n  virtual void mutate() { x = x * 2; }\n};\nclass B : public A {\npublic:\n  B(int v) : A(v) {}\n  void mutate() { x = x + 100; }\n};\nvoid process(A& obj) {\n  obj.mutate();\n  obj.mutate();\n  cout << obj.x;\n}\nint main() {\n  A a(5);\n  B b(5);\n  process(a);\n  process(b);\n}', '20205');

  add('oneword', 'What is the output?\n\nclass Token {\n  char ch;\npublic:\n  Token(char c) : ch(c) { cout << "+" << ch; }\n  Token(const Token& o) : ch(o.ch) { cout << "c" << ch; }\n  ~Token() { cout << "-" << ch; }\n};\nToken make(char c) { return Token(c); }\nint main() {\n  Token a = make(\'X\');\n  Token b(\'Y\');\n  Token c = b;\n}', '+X+YcY-Y-Y-X');

  add('oneword', 'What is the output?\n\nclass Matrix {\n  int r, c;\npublic:\n  Matrix(int r, int c) : r(r), c(c) { cout << r << "x" << c; }\n  Matrix operator*(const Matrix& o) const {\n    return Matrix(r, o.c);\n  }\n};\nint main() {\n  Matrix a(2,3), b(3,4);\n  cout << "|";\n  Matrix c = a * b;\n}', '2x33x4|2x4');

  add('oneword', 'What is the output?\n\nclass Node {\npublic:\n  int val;\n  Node* next;\n  Node(int v, Node* n = nullptr) : val(v), next(n) {}\n};\nvoid printList(Node* h) {\n  while(h) { cout << h->val; h = h->next; }\n}\nint main() {\n  Node c(3), b(2, &c), a(1, &b);\n  Node* head = &a;\n  // Reverse\n  Node* prev = nullptr;\n  Node* cur = head;\n  while(cur) {\n    Node* nxt = cur->next;\n    cur->next = prev;\n    prev = cur;\n    cur = nxt;\n  }\n  printList(prev);\n}', '321');

  add('oneword', 'What is the output?\n\nclass Pair {\n  int a, b;\npublic:\n  Pair(int x, int y) : a(x), b(y) {}\n  Pair operator+(const Pair& o) const { return Pair(a+o.a, b+o.b); }\n  bool operator==(const Pair& o) const { return a==o.a && b==o.b; }\n  friend ostream& operator<<(ostream& os, const Pair& p) {\n    return os << "(" << p.a << "," << p.b << ")";\n  }\n};\nint main() {\n  Pair a(1,2), b(3,4);\n  Pair c = a + b;\n  cout << c << (c == Pair(4,6));\n}', '(4,6)1');

  add('oneword', 'What is the output?\n\nclass Handler {\npublic:\n  virtual bool canHandle(int code) = 0;\n  virtual void handle(int code) = 0;\n  virtual ~Handler() {}\n};\nclass Low : public Handler {\npublic:\n  bool canHandle(int code) { return code < 10; }\n  void handle(int code) { cout << "L" << code; }\n};\nclass High : public Handler {\npublic:\n  bool canHandle(int code) { return code >= 10; }\n  void handle(int code) { cout << "H" << code; }\n};\nint main() {\n  Handler* chain[] = { new Low(), new High() };\n  int codes[] = { 5, 15, 3 };\n  for(int c : codes)\n    for(Handler* h : chain)\n      if(h->canHandle(c)) { h->handle(c); break; }\n}', 'L5H15L3');

  add('oneword', 'What is the output?\n\nclass Wrap {\n  int* ptr;\npublic:\n  Wrap(int v) : ptr(new int(v)) {}\n  Wrap(Wrap&& o) noexcept : ptr(o.ptr) { o.ptr = nullptr; cout << "M"; }\n  ~Wrap() { if(ptr) { cout << *ptr; delete ptr; } else cout << "N"; }\n};\nint main() {\n  Wrap a(7);\n  Wrap b(std::move(a));\n}', 'MN7');

  add('oneword', 'What is the output?\n\nclass Base {\nprotected:\n  int x;\npublic:\n  Base(int v) : x(v) {}\n  virtual int val() { return x; }\n};\nclass Left : virtual public Base {\npublic:\n  Left(int v) : Base(v) {}\n  int val() { return x + 1; }\n};\nclass Right : virtual public Base {\npublic:\n  Right(int v) : Base(v) {}\n  int val() { return x + 2; }\n};\nclass Bottom : public Left, public Right {\npublic:\n  Bottom(int v) : Base(v), Left(v), Right(v) {}\n  int val() { return Left::val() + Right::val(); }\n};\nint main() {\n  Base* p = new Bottom(10);\n  cout << p->val();\n}', '23');

  add('oneword', 'What is the output?\n\nstruct Item {\n  int priority;\n  const char* name;\n};\nvoid insertionSort(Item arr[], int n) {\n  for(int i = 1; i < n; i++) {\n    Item key = arr[i];\n    int j = i - 1;\n    while(j >= 0 && arr[j].priority > key.priority) {\n      arr[j+1] = arr[j];\n      j--;\n    }\n    arr[j+1] = key;\n  }\n}\nint main() {\n  Item items[] = {{3,"C"},{1,"A"},{2,"B"}};\n  insertionSort(items, 3);\n  for(int i=0;i<3;i++) cout << items[i].name;\n}', 'ABC');

  add('oneword', 'What is the output?\n\nclass Event {\n  static int seq;\n  int id;\n  string type;\npublic:\n  Event(string t) : type(t), id(seq++) {}\n  void fire() { cout << type[0] << id; }\n};\nint Event::seq = 0;\nint main() {\n  Event a("click"), b("hover"), c("click");\n  b.fire();\n  a.fire();\n  c.fire();\n}', 'h1c0c2');

  await adminService.seedQuestionsForLevel(level, questions);
  console.log('Level 9 seeded with 100 questions (85 oneword + 15 mcq)!');
  await app.close();
}

bootstrap().catch(console.error);
