services:
  - type: web
    name: classwars
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:frontend && npm run build:backend
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ONECOMPILER_RAPIDAPI_KEY
        sync: false
      - key: PORT
        value: 10000
